### PR TITLE
Added edit/deletion tracking

### LINKED ISSUE #5: Add edit/deletion tracking
I think the easiest way to do this is to add a field to `packingSlip` and `shipment` schemas: `isEdit: Boolean`.

Whenever an edit happens we make a copy (new `_id`) of the current document with `{ isEdit: false }` (at most 1) and set its flag to `true`.
Then make the requested changes to the original document.

In case of a deletion, just delete all fields except the user tracking field.

### PR DESCRIPTION
**Pull request by jbolles94**
Closes #5

### CODE REVIEW

**Review by jarrilla — CHANGES_REQUESTED** [review]
Deleting an item from a packing slip is an issue as it is creating a copy both when the delete endpoint is hit, and then again when OK is hit.

I think the solution is to probably not generate a copy when that particular endpoint is hit since a modified copy is being generated anyways once the changes are committed.

*EDIT*: just noticed another issue!
- The `isPastVersion: true` documents are being used to tally the `fulfilledQties` so every edit that is made is incrementing those fulfillment quantities !

Otherwise this looks good!

**Comment by jbolles94** [comment]
> Deleting an item from a packing slip is an issue as it is creating a copy both when the delete endpoint is hit, and then again when OK is hit.
> 
> I think the solution is to probably not generate a copy when that particular endpoint is hit since a modified copy is being generated anyways once the changes are committed.
> 
> _EDIT_: just noticed another issue!
> 
> * The `isPastVersion: true` documents are being used to tally the `fulfilledQties` so every edit that is made is incrementing those fulfillment quantities !
> 
> Otherwise this looks good!

@jarrilla I believe I have addressed your edit. Good catch on that. Just needed to filter those out when we were populating the work orders. 

As for the original comment, we are hitting the same endpoint for both the delete of an item in a packing slip and hitting the OK button, so I don't think I can not make a blanket copy since there is no difference between a deletion or an edit from the backend's perspective. My thoughts were to instead prevent an edit endpoint from getting hit on the FE when there are no edits and also doing a double check on the receiving end of the backend. If nothing is changing then we won't make the edit or the copy. Does this sound like a good approach to you? Or would you prefer something else?

**Comment by jbolles94** [comment]
> @jbolles94 I think the biggest issue with those deletions is that ideally we shouldn't be hitting the backend with a delete request until we hit the OK button.
> 
> Otherwise, for example, we may delete a couple things, change our mind, and hit cancel, but the deletions will have already gone through.
> 
> If I understood you correctly, I think this is the opposite of what you described above. I.e. the FE shouldn't commit a change until we hit OK (instead of cancel).

Sounds like the fix for the issue is a FE thing. I will work on the FE only issuing the final deletes when we hit the OK on the form dialog instead of on the confirm dialog. If we do that, I think that addresses the original issue that you brought up here. Let me know if there are any other issues with this PR, but if there aren't then I think this should be ready for merge.

**Comment by jarrilla** [comment]
Agreed. Could you have a look at the conflicts?

Be extra careful, the pipeline changed a bit due to a bug (see https://github.com/conturo-prototyping/pack-ship-server/commit/02b9b58e983056d0e6403d5f9c9051e2693b359c)

**Comment by jbolles94** [comment]
> Agreed. Could you have a look at the conflicts?
> 
> Be extra careful, the pipeline changed a bit due to a bug (see #15)

@jarrilla Conflicts should be handled. I also created https://github.com/conturo-prototyping/pack-ship-client/pull/43 to handle the case we talked about for packingslips and shipments.

**Comment by jarrilla** [comment]
@joshplumley 
This doesn't seem to be handling errors.

In particular, I'm looking at deleting a packing slip that exists in a shipment (which is forbidden and throws a 400 error).

Instead I'm seeing "Packing slip deleted" when it's not actually being deleted.

**Pull request merged**
