### PR TITLE
Get lots whole router mq 13

### PR DESCRIPTION
**Pull request by joshplumley**
Added GET /lot/:lotId/route and tests.
Fixed Linter issues

### CODE REVIEW

**Comment by jarrilla** [comment]
This was based from a closed PR.. might be better to redo ?

**Review by jarrilla — CHANGES_REQUESTED** [review]
See above.

**Comment by joshplumley** [comment]
Yea, ill fix this up.

**Comment by joshplumley** [comment]
Closing in favor of #120

**Pull request closed without merging**
